#!/usr/bin/env python3
"""Transmit simulated GNSS data via UHD."""
import argparse

from gnuradio import blocks, gr, uhd
from gnuradio.eng_option import eng_option

block_istc = blocks.interleaved_short_to_complex


class top_block(gr.top_block):
    def __init__(self, options):
        gr.top_block.__init__(self, "SIREN-UHD")

        self.uhd_usrp_sink = uhd.usrp_sink(
            options.args, uhd.stream_args(cpu_format="fc32"))
        self.uhd_usrp_sink.set_samp_rate(options.sample_rate)
        self.uhd_usrp_sink.set_center_freq(options.frequency, 0)
        self.uhd_usrp_sink.set_gain(options.gain, 0)
        self.uhd_usrp_sink.set_clock_source(options.clock_source)

        if options.bits == 16:
            # a file source for the file generated by the siren
            self.blocks_file_source = blocks.file_source(
                gr.sizeof_short*1, options.file, True)
            # convert from interleaved short to complex values
            self.blocks_interleaved_short_to_complex = block_istc(False, False)
            # establish the connections
            self.connect(
                (self.blocks_file_source, 0),
                (self.blocks_interleaved_short_to_complex, 0)
            )
        else:
            # a file source for the file generated by the siren
            self.blocks_file_source = blocks.file_source(
                gr.sizeof_char*1, options.file, True
            )
            # convert from signed bytes to short
            self.blocks_char_to_short = blocks.char_to_short(1)
            # convert from interleaved short to complex values
            self.blocks_interleaved_short_to_complex = block_istc(False, False)
            # establish the connections
            self.connect(
                (self.blocks_file_source, 0), (self.blocks_char_to_short, 0)
            )
            self.connect(
                (self.blocks_char_to_short, 0),
                (self.blocks_interleaved_short_to_complex, 0)
            )

        # scale complex values to within +/- 1.0 so don't overflow USRP DAC
        # scale of 1.0/2**11 will scale it to +/- 0.5
        self.blocks_multiply_const = blocks.multiply_const_vcc((1.0/2**11, ))

        # establish the connections
        self.connect(
            (self.blocks_interleaved_short_to_complex, 0),
            (self.blocks_multiply_const, 0)
        )
        self.connect((self.blocks_multiply_const, 0), (self.uhd_usrp_sink, 0))


def main():
    """Main function."""
    args = init_args()
    tb = top_block(args)
    tb.start()
    input('Press Enter to quit: ')
    tb.stop()
    tb.wait()


def init_args():
    """Initilize function, parse user input."""
    # initilize a argument parser
    parser = argparse.ArgumentParser(
        description="Transmit simulated GNSS data via UHD",
        epilog="Example: %(prog)s gnsssim.iq -f 1561.098e6 -g 75 -b 8 -s 5.0e6"
    )
    # add arguments
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s 0.1.0')
    parser.add_argument('file', metavar='<file>', type=str,
                        help='simulated data output by siren')
    parser.add_argument('-frequency', metavar='<freq>', required=True,
                        type=float, help='transmit frequency (Hz)')
    parser.add_argument('-gain', metavar='<gain>', default=0.0, type=float,
                        help='transmitter gain [default: 0]')
    # On USRP2, the sample rate should lead to an even decimator based on
    # the 100 MHz clock. At 2.5 MHz, we end up with 40
    parser.add_argument('-sample', metavar='<samp>', default=2.5e6, type=float,
                        help='sample rate of data [default: 2.5MHz]')
    parser.add_argument('-bits', metavar='<bit>', default=16, choices=[8, 16],
                        help='size of every sample [default: 16]')
    parser.add_argument('-args', metavar='<args>', default='',
                        help='UHD arguments [default: None]')
    parser.add_argument('-clock', metavar='<clock>', default='internal',
                        help='clock source [default: internal, external]')

    return parser.parse_args()


if __name__ == '__main__':
    main()
